# Default values for registry.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/apigee/registry-server
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

logging: "info"

database:
  driver: "postgres"
  config: 
    host: "data-postgresql.registry.svc.cluster.local"
    port: "5432"
    dbname: "postgres"
    user: "postgres"
    password: "$PGPASSWD"
    sslmode: "disable"

podAnnotations: {}

service:
  type: ClusterIP
  port: 80

autoscaling:
  enabled: false

nodeSelector:
  kubernetes.io/arch: amd64

tolerations: []

affinity: {}

